### ISSUE TITLE
Wireless Crafting Terminal (WCT 2 mod) 

### ISSUE THREAD

**Issue by mtimyself** [NillerMedDild/Enigmatica2Expert#293]
**Issue Description**

When using the hotkey to open the WCT (in head bauble slot), and only when using the hotkey, the terminal does not open (ever). It requires an additional input (e.g. movement forwards) to open.
This issue is brand new on 1.39 and was not experienced previously on 1.37 (1.38 was never deployed to the server).

Additionally the render in world is broken when in a TC's item rack, but not an item frame for example. This worked fine in the previous version. (See screenshot below).

Also, and I realize this sounds very generic, the darned thing has a tendency to just disappear when moving it in and out of the inventory. I suspect the "auto replenish" thing that moves the next item/stack to your hotbar might be involved since this happend when I had more than 1 in my inventory and tried placing it in different containers to test the render bug. I have lost 2 of them so far and they do not reappear (not a sync issue).

**Modpack version (Do not use "latest")**
1.39

**Logs**

Nothing regarding this in latest.log

**Screenshots**
 
http://prntscr.com/l2szhu

**Additional context**

Can not further isolate the issue. Happens no matter what.

**Comment by p455w0rd** [comment]
sorry for the delay...hurricane destroyed my home...at any rate, thank you for the report, I'm in the middle of 100% rewriting WCT atm..no ETA on next update...but as soon as I can get it out, it'll be on Curse/Twitch Desktop

**Comment by NillerMedDild** [comment]
That's an alright excuse :P I hope you've got a decent setup again.

**Comment by SuperKael** [comment]
Hey! I suppose this probably doesn't matter if the mod is being completely re-written, but I'd like to add that this bug only occurs if the hotkey is bound to a mouse button, and not a key on the keyboard. I have it bound to 'Mouse 4' and this problem occurs, but if I change it to a key it works as expected.

**Comment by p455w0rd** [comment]
just keeping the issue alive..I want to be sure to get this fixed in the next update

**Comment by p455w0rd** [comment]
update WCT :D (also WFT has been removed for now and will be its own mod soon)

**Comment by NillerMedDild** [comment]
I trust that you solved the issue :D I'll update asap, when ExtraCells does.

**Comment by BlazingPL** [comment]
It still happens on E2E 1.53 server with the lastest Wireless Crafting build.

**Comment by NillerMedDild** [comment]
That's because of ExtraCells. #616
